"""SCPI-like command constants used by the Keysight U1242C serial interface."""

IDN = "*IDN?"
STATUS = "STAT?"
CONFIGURATION = "CONF?"
BATTERY = "SYST:BATT?"
FETCH = "FETC?"
RESET = "*RST"
BEEP = "SYST:BEEP"
BACKLIGHT_ON = "SYST:BLIT 1"
BACKLIGHT_OFF = "SYST:BLIT 0"

QUERY_COMMANDS = frozenset({IDN, STATUS, CONFIGURATION, BATTERY, FETCH})
SIDE_EFFECT_COMMANDS = frozenset({RESET, BEEP, BACKLIGHT_ON, BACKLIGHT_OFF})
